### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by nanofi** [Natomix/CharacterRestyler#1]
Hi.

I recommend you to use `InitializeLoaders` instead of `InitializeGameLoaders` for adding a chat command.  Coroutines added to `InitializeGameLoaders` will be called each time the game scene is loaded. This means that when we go back to the title scene and start the game again, these coroutines will be called. On the other hand, coroutines added to `InitializerLoaders` will be called once the game scene is loaded. Because the chat command manager keeps all the chat commands until end of the game application, we should add chat command only once. 

I'm sorry for theconfusion about my design of the initialization interface.

Thank you for using LibCraftopia.

**Comment by Natomix** [comment]
Oh right, thanks for letting me know I will update that at once. :)
